# API key
api_key:

# timeout the IP ip_cache in seconds
cache_timeout: 86400

# Greynoise Tag IDs and corresponding names
tags:
  A10_NETWORKS: A10 Networks
  ADB_WORM: ADB Worm
  AHREFS: Ahrefs
  AIHIT: aiHit
  AMPERE_INNOTECH: Ampere Innotech
  ARCHIVE: Archive.org
  ASTERISK_BRUTEFORCER: Asterisk Bruteforcer
  AVTECH_IP_CAMERA_WORM: Avtech IP Camera Worm
  BAIDU_SPIDER: Baidu Spider
  BELKIN_N750_WORM_CVE_2014_1635: Belkin N750 Worm CVE-2014-1635
  BINARYEDGE: BinaryEdge.io
  BINGBOT: BingBot
  BITCOIN_NODE_SCANNER_HIGH: Bitcoin Node Scanner
  BITCOIN_NODE_SCANNER_LOW: Bitcoin Node Scanner
  BROWN_UNIVERSITY: Brown University
  CAMBRIDGE_CYBERCRIME_CENTRE: Cambridge Cybercrime Centre
  CASSANDRA_SCANNER_HIGH: Cassandra Scanner
  CASSANDRA_SCANNER_LOW: Cassandra Scanner
  CCBOT: CCBot
  CENSYS: Censys
  CENSYS: Censys
  CGI_SCRIPT_SCANNER: CGI Script Scanner
  CHECKMARKNETWORK: CheckMarkNetwork
  CHINANET_SSH_BRUTEFORCER: CHINANET SSH Bruteforcer
  CLIQZ: Cliqz
  CLOUD_SYSTEM_NETWORKS: Cloud System Networks
  COBALT_STRIKE_SCANNER_HIGH: Cobalt Strike Scanner
  COBALT_STRIKE_SCANNER_LOW: Cobalt Strike Scanner
  COCCOC: Coc Coc
  COMPANYBOOK: CompanyBook
  COMPROMISED_RASPBERRY_PI: Compromised Raspberry Pi
  COUNTERSTRIKE_SERVER_SCANNER_HIGH: CounterStrike Server Scanner
  COUNTERSTRIKE_SERVER_SCANNER_LOW: CounterStrike Server Scanner
  CPANEL_SCANNER_HIGH: CPanel Scanner
  CPANEL_SCANNER_LOW: CPanel Scanner
  CYBERGREEN: CyberGreen
  DATAPROVIDER: DataProvider
  DLINK_2750B_WORM: D-Link 2750B Worm
  DLINK_850L_WORM: D-Link 850L Worm
  DNS_SCANNER_HIGH: DNS Scanner
  DNS_SCANNER_LOW: DNS Scanner
  DOCKERD_SCANNER_HIGH: Dockerd Scanner
  DOCKERD_SCANNER_LOW: Dockerd Scanner
  DOMAINTOOLS: DomainTools
  DRUPAL_CVE_2018_7600_WORM: Drupal CVE-2018-7600 Worm
  EIR_D1000_ROUTER_WORM: Eir D1000 Router Worm
  ELASTICSEARCH_SCANNER: Elasticsearch Scanner
  ELASTICSEARCH_SCANNER_HIGH: Elasticsearch Scanner
  ELASTICSEARCH_SCANNER_LOW: Elasticsearch Scanner
  EMBEDDED_DEVICE_WORM: Embedded Device Worm
  ETHEREUM_NODE_SCANNER_HIGH: Ethereum Node Scanner
  ETHEREUM_NODE_SCANNER_LOW: Ethereum Node Scanner
  EXPOSURE_MONITORING: ExposureMonitoring
  FACEBOOK_NETPROBE: Facebook NetProbe
  FAST_HTTP_AUTH_SCANNER_CLIENT: Fast HTTP Auth Scanner Client
  FINDMALWARE: FindMalware
  FTP_BRUTEFORCER: FTP Bruteforcer
  FTP_SCANNER_HIGH: FTP Scanner
  FTP_SCANNER_LOW: FTP Scanner
  GOOGLEBOT: GoogleBot
  GO_HTTP_CLIENT: Go HTTP Client
  GO_SSH_SCANNER: Go SSH Scanner
  GPON_CVE_2018_10561_ROUTER_WORM: GPON CVE-2018-10561 Router Worm
  HADOOP_YARN_WORM: Hadoop Yarn Worm
  HTTP_ALT_SCANNER_HIGH: HTTP Alt Scanner
  HTTP_ALT_SCANNER_LOW: HTTP Alt Scanner
  HUAWEI_HG532_UPNP_WORM_CVE_2017_17215: Huawei HG532 UPnP Worm CVE-2017-17215
  IBM_OBOT: IBM oBot
  IIS_WEBDAV_REMOTE_CODE_EXECUTION_CVE_2017_7269: IIS WebDAV Remote Code Execution CVE-2017-7269
  IMAP_SCANNER_HIGH: IMAP Scanner
  IMAP_SCANNER_LOW: IMAP Scanner
  INTERNET_CENSUS: Internet Census
  INTRINSEC: Intrinsec
  IOT_MQTT_SCANNER_HIGH: IOT MQTT Scanner
  IOT_MQTT_SCANNER_LOW: IOT MQTT Scanner
  IPIP: ipip.net
  IPSEC_VPN_SCANNER_HIGH: IPSec VPN Scanner
  IPSEC_VPN_SCANNER_LOW: IPSec VPN Scanner
  JAVA_HTTP_CLIENT: Java HTTP Client
  JBOSS_WORM: Jboss Worm
  JORGEE_HTTP_SCANNER: Jorgee HTTP Scanner
  LDAP_SCANNER_HIGH: LDAP Scanner
  LDAP_SCANNER_LOW: LDAP Scanner
  LINKSYS_E_SERIES_THEMOON_ROUTER_WORM: Linksys E-Series TheMoon Router Worm
  LINK_NET_LW_N605R_WORM_CVE_2018_16752: LINK-NET LW-N605R Worm CVE-2018-16752
  LITECOIN_NODE_SCANNER_HIGH: LiteCoin Node Scanner
  LITECOIN_NODE_SCANNER_LOW: LiteCoin Node Scanner
  LOSEC: LoSec
  MAIL_RU: Mail.RU
  MASSCAN_CLIENT: Masscan Client
  MAUIBOT: MauiBot
  MEMCACHED_SCANNER_HIGH: Memcached Scanner
  MEMCACHED_SCANNER_LOW: Memcached Scanner
  MINECRAFT_SCANNER_HIGH: Minecraft Scanner
  MINECRAFT_SCANNER_LOW: Minecraft Scanner
  MIRAI: Mirai
  MJ12BOT: MJ12bot
  MOJEEK: Mojeek
  MONGODB_SCANNER_HIGH: MongoDB Scanner
  MONGODB_SCANNER_LOW: MongoDB Scanner
  MOZ_DOTBOT: Moz DotBot
  MSSQL_BRUTEFORCER: MSSQL Bruteforcer
  MSSQL_SCANNER_HIGH: MSSQL Scanner
  MSSQL_SCANNER_LOW: MSSQL Scanner
  MYSQL_SCANNER_HIGH: MySQL Scanner
  MYSQL_SCANNER_LOW: MySQL Scanner
  NETBIOS_SCANNER_HIGH: NETBIOS Scanner
  NETBIOS_SCANNER_LOW: NETBIOS Scanner
  NETCRAFT: NetCraft
  NETIS_ROUTER_ADMIN_SCANNER_HIGH: Netis Router Admin Scanner
  NETIS_ROUTER_ADMIN_SCANNER_LOW: Netis Router Admin Scanner
  NET_SYSTEMS_RESEARCH: Net Systems Research
  NMAP: Nmap
  NTP_SCANNER_HIGH: NTP Scanner
  NTP_SCANNER_LOW: NTP Scanner
  ONYPHE: ONYPHE
  OPENLINKPROFILER: OpenLinkProfiler
  OPEN_PROXY_SCANNER: Open Proxy Scanner
  ORACLE_WEBLOGIC_CVE_2017_10271_WORM: Oracle WebLogic CVE-2017-10271 Worm
  PANSCIENT: Panscient
  PDRLABS: PDRLabs.net
  PHPMYADMIN_WORM: PHPMyAdmin Worm
  PHP_WORM: PHP Worm
  PINGDOM: Pingdom.com
  PINGZAPPER: PingZapper
  PING_SCANNER_HIGH: Ping Scanner
  PING_SCANNER_LOW: Ping Scanner
  PING_SCANNER_LOW: Ping Scanner
  POP3_SCANNER_HIGH: POP3 Scanner
  POP3_SCANNER_LOW: POP3 Scanner
  POSTGRES_BRUTEFORCER: Postgres Bruteforcer
  POSTGRES_SCANNER_HIGH: Postgres Scanner
  POSTGRES_SCANNER_LOW: Postgres Scanner
  PPTP_VPN_SCANNER_HIGH: PPTP VPN Scanner
  PPTP_VPN_SCANNER_LOW: PPTP VPN Scanner
  PRINTER_SCANNER_HIGH: Printer Scanner
  PRINTER_SCANNER_LOW: Printer Scanner
  PRIVOXY_PROXY_SCANNER_HIGH: Privoxy Proxy Scanner
  PRIVOXY_PROXY_SCANNER_LOW: Privoxy Proxy Scanner
  PROBETHENET: ProbeTheNet.com
  PROJECT25499: Project25499
  PROJECT_SONAR: Project Sonar
  PROXYBROKER: ProxyBroker
  PYCURL_HTTP_CLIENT: PycURL HTTP Client
  PYTHON_REQUESTS_CLIENT: Python Requests Client
  QUADMETRICS: Quadmetrics.com
  QWANT: Qwant
  RABBITMQ_SCANNER_HIGH: RabbitMQ Scanner
  RABBITMQ_SCANNER_LOW: RabbitMQ Scanner
  RDP_SCANNER_HIGH: RDP Scanner
  RDP_SCANNER_LOW: RDP Scanner
  REALTEK_MINIIGD_UPNP_WORM_CVE_2014_8361: Realtek Miniigd UPnP Worm CVE-2014-8361
  REDIS_SCANNER_HIGH: Redis Scanner
  REDIS_SCANNER_LOW: Redis Scanner
  RESIDENTIAL: Residential
  RIDDLER: Riddler.io
  ROUTER_RPC_SCANNER_HIGH: Router RPC Scanner
  ROUTER_RPC_SCANNER_LOW: Router RPC Scanner
  RUHR_UNIVERSITTT_BOCHUM: Ruhr-Universitat Bochum
  RWTH_AACHEN_UNIVERSITY: RWTH AACHEN University
  SAFEDNS: SafeDNS
  SEMRUSH: SEMrush
  SEZNAM: Seznam
  SHADOWSERVER: ShadowServer.org
  SHODAN: Shodan.io
  SIEMENS_PLC_SCANNER_HIGH: Siemens PLC Scanner
  SIEMENS_PLC_SCANNER_LOW: Siemens PLC Scanner
  SITEEXPLORER: SiteExplorer
  SMB_SCANNER_HIGH: SMB Scanner
  SMB_SCANNER_LOW: SMB Scanner
  SMTP_SCANNER_HIGH: SMTP Scanner
  SMTP_SCANNER_LOW: SMTP Scanner
  SNMP_SCANNER_HIGH: SNMP Scanner
  SNMP_SCANNER_LOW: SNMP Scanner
  SOCKS_PROXY_SCANNER_HIGH: SOCKS Proxy Scanner
  SOCKS_PROXY_SCANNER_LOW: SOCKS Proxy Scanner
  SOGOU: Sogou
  SQUID_PROXY_SCANNER_HIGH: Squid Proxy Scanner
  SQUID_PROXY_SCANNER_LOW: Squid Proxy Scanner
  SSDP_UPNP_SCANNER_HIGH: SSDP/UPNP Scanner
  SSDP_UPNP_SCANNER_LOW: SSDP/UPNP Scanner
  SSH_SCANNER_HIGH: SSH Scanner
  SSH_SCANNER_LOW: SSH Scanner
  SSH_WORM_HIGH: SSH Worm
  SSH_WORM_LOW: SSH Worm
  STANFORD_UNIVERSITY: Stanford University
  STATASTICO: Statastico
  STRETCHOID: Stretchoid.com
  TALAIA: Talaia
  TEAM_CYMRU: Team Cymru
  TELNET_SCANNER_HIGH: Telnet Scanner
  TELNET_SCANNER_LOW: Telnet Scanner
  TELNET_WORM_HIGH: Telnet Worm
  TELNET_WORM_LOW: Telnet Worm
  TFTP_SCANNER_HIGH: TFTP Scanner
  TFTP_SCANNER_LOW: TFTP Scanner
  TOR: Tor
  UNAUTHENTICATED_REDIS_WORM: Unauthenticated Redis Worm
  UNIVERSITY_OF_CALIFORNIA_BERKELEY: University of California Berkeley
  UNIVERSITY_OF_MICHIGAN: University of Michigan
  UNIVERSITY_OF_NEW_MEXICO: University of New Mexico
  UNKNOWN_LINUX_WORM: Unknown Linux Worm
  UPTIME: Uptime.com
  VNC_BRUTEFORCER: VNC Bruteforcer
  VNC_SCANNER_HIGH: VNC Scanner
  VNC_SCANNER_LOW: VNC Scanner
  VOIP_SCANNER_HIGH: VOIP Scanner
  VOIP_SCANNER_LOW: VOIP Scanner
  WEB_CRAWLER: Web Crawler
  WEB_SCANNER_HIGH: Web Scanner
  WEB_SCANNER_LOW: Web Scanner
  WHATWEB_SCANNER: WhatWeb Scanner
  WINDOWS_RDP_COOKIE_HIJACKER_CVE_2014_6318: Windows RDP Cookie Hijacker CVE-2014-6318
  WINRM_SCANNER_HIGH: WinRM Scanner
  WINRM_SCANNER_LOW: WinRM Scanner
  WORDPRESS_WORM: Wordpress Worm
  WORDPRESS_XML_RPC_WORM: Wordpress XML RPC Worm
  WinRM_SCANNER_LOW: WinRM Scanner
  YANDEX_SEARCH_ENGINE: Yandex Search Engine
  ZGRAB_SSH_SCANNER: ZGrab SSH Scanner
  ZMAP_CLIENT: ZMap Client
  ZMEU_WORM: ZmEu Worm
  ZYXEL_OS_COMMAND_INJECTION_CVE_2017_6884: Zyxel OS Command Injection CVE-2017-6884
